export { Observable, observable } from './reactivity/observable'
export { watch } from './reactivity/watch'
export { computed } from './reactivity/computed'
export { html, render } from './template/html'
export { repeat } from './template/repeat'
// export { html } from './template/html'
